Code sanitation: added mandatory local git hook

diff --git a/check_code b/check_code
--- a/check_code
+++ b/check_code
@@ -1,12 +1,17 @@
 #!/bin/bash
 
-# Stop at first error
-set -e
+echo -e "Checking code with flake8\c"
+flake_result=$(flake8 src tests)
+flake_status=$?
 
-echo -e "\033[32mChecking code with flake8\033[0m"
-flake8 src tests
+if [ $flake_status -eq 0 ]
+then
+    echo -e " \033[34m(success)\033[0m"
+else
+    echo -e " \033[33m(failure)\033[0m"
+fi
 
-echo -e "\033[32mChecking code with pylint\033[0m"
+echo -e "Checking code with pylint\c"
 # --good-names => whitelist of variables
 # -rn => 
 # -iy => include msgids
@@ -24,12 +29,27 @@ echo -e "\033[32mChecking code with pylint\033[0m"
 # R0201 Method could be a function (i.e. does not use self)
 # R0914 Too many local variables (16/15)
 
-PYTHONPATH=$PYTHONPATH:.:./src pylint \
+pylint_result=$(PYTHONPATH=$PYTHONPATH:.:./src pylint \
     --good-names=x,y,X,Y,e,i,j \
     -rn \
     -iy \
     -dC0111,R0904,R0922,W0511,W0403,R0801,I0011,W0105,W0107,W0613,R0201,R0914 \
     --module-rgx="(([a-z_][a-z0-9_]*)|([A-Z][a-zA-Z0-9]+)|(test_[a-zA-Z0-9]+))$" \
-    src tests
+    src tests)
+pylint_status=$?
 
-echo -e "\033[32mCode has been found to be correct\033[0m"
+if [ $pylint_status -eq 0 ]
+then
+    echo -e " \033[34m(success)\033[0m"
+else
+    echo -e " \033[33m(failure)\033[0m"
+fi
+
+if [ $flake_status -eq 0 ] && [ $pylint_status -eq 0 ]
+then
+    echo -e "\033[32mCode was good, you can commit this.\033[0m"
+else
+    echo $flake_result
+    echo $pylint_result
+    echo -e "\033[31mCode was not conformant. If you really want to commit, you can use --no-verify.\033[0m"
+fi
